# Generated by Django 4.0.5 on 2022-07-02 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='stocks',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rbdx.stock'),
        ),
    ]
