# Generated by Django 4.0.5 on 2022-07-02 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0002_index_stocks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='stocks',
        ),
        migrations.AddField(
            model_name='stock',
            name='index',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rbdx.index'),
        ),
    ]
