# Generated by Django 4.0.5 on 2022-07-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='symbol',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
