# Generated by Django 4.0.5 on 2022-07-03 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0006_stock_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='weight',
        ),
    ]
