# Generated by Django 4.0.5 on 2022-07-05 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0007_remove_stock_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keyId',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='secretKey',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
