# Generated by Django 4.0.5 on 2022-07-06 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0009_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='account',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='rbdx.account'),
        ),
    ]
