# Generated by Django 4.0.5 on 2022-07-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0012_alter_usermodel_email_alter_usermodel_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
