# Generated by Django 4.0.5 on 2022-07-13 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0013_alter_usermodel_is_staff'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='user',
        ),
    ]
