# Generated by Django 4.0.5 on 2022-07-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0014_alter_usermodel_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='key_id',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='usermodel',
            name='secret_key',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
