# Generated by Django 4.0.5 on 2022-07-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0018_alter_usermodel_key_id_alter_usermodel_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='key_id',
            field=models.CharField(default='1', max_length=200),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='secret_key',
            field=models.CharField(default='1', max_length=200),
        ),
    ]
