# Generated by Django 4.0.5 on 2022-07-13 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0021_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='key_id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='account',
            name='secret_key',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
