# Generated by Django 4.0.5 on 2022-07-16 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0023_alter_account_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
