# Generated by Django 4.0.5 on 2022-07-19 09:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0034_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 11, 52, 24, 675786)),
        ),
    ]
