# Generated by Django 4.0.5 on 2022-07-19 09:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0040_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 19, 9, 54, 11, 727037, tzinfo=utc)),
        ),
    ]
