# Generated by Django 4.0.5 on 2022-07-19 09:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0041_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 7, 19, 9, 55, 40, 786098, tzinfo=utc)),
        ),
    ]
