# Generated by Django 4.0.5 on 2022-07-19 09:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0042_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
