# Generated by Django 4.0.5 on 2022-07-19 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0043_alter_stock_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='actualWeight',
            field=models.FloatField(default=0),
        ),
    ]
