# Generated by Django 4.0.5 on 2022-07-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0044_stock_actualweight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='indexShort',
        ),
        migrations.AddField(
            model_name='index',
            name='symbol',
            field=models.CharField(default=None, max_length=5),
        ),
    ]
