# Generated by Django 4.0.5 on 2022-09-22 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbdx', '0046_plan_account_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='rbdx.plan'),
        ),
    ]
