# Generated by Django 4.0.5 on 2022-10-17 14:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import roboadvisor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('sys_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=127, unique=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_premium', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'user',
            },
            managers=[
                ('objects', roboadvisor.models.MyUserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_id', models.CharField(default=None, max_length=200, unique=True)),
                ('secret_key', models.CharField(default=None, max_length=200, unique=True)),
                ('name', models.CharField(default=None, max_length=200, unique=True)),
                ('balance', models.FloatField()),
                ('totalEquity', models.FloatField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=5)),
                ('marketCap', models.FloatField(default=0)),
                ('equity', models.FloatField(default=10000)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roboadvisor.account')),
            ],
        ),
        migrations.CreateModel(
            name='IndexShort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(default=None, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=5)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('marketCap', models.FloatField()),
                ('actualWeight', models.FloatField(default=0)),
                ('index', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roboadvisor.index')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=100)),
                ('codeStatus', models.CharField(max_length=100)),
                ('totalPurchase', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nameClient', models.CharField(max_length=100)),
                ('lastNameClient', models.CharField(max_length=100)),
                ('emailClient', models.EmailField(max_length=100)),
                ('adressClient', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('stock', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='roboadvisor.stock')),
            ],
        ),
    ]
