# Generated by Django 4.0.5 on 2022-10-26 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0002_remove_purchase_user_purchase_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='stock',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='roboadvisor.stock'),
        ),
    ]
