# Generated by Django 4.0.5 on 2022-10-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roboadvisor', '0002_purchase_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='equity',
        ),
    ]
